### ISSUE TITLE
Exit code is always 0, even when tests fail

### ISSUE THREAD

**Issue by timwis** [bendrucker/tape-istanbul#11]
I noticed with yoshuawuyts/choo#356 that the CI server was marking pull requests as 'passed' despite a test failing. On further investigation, it looks like once the test is passed to `tape-istanbul`, it will always return exit code `0`, even if a test fails.

I tried on a basic test case - here's `test.js`:

```javascript
'use strict'

const test = require('tape')

test('test fixture', function (t) {
  t.equal(fixture(true), 1)
  t.equal(fixture(), 2)
  t.end()
})

function fixture (a) {
  return a ? 1 : 3
}
```

Running it via:
```bash
browserify test.js -p tape-istanbul/plugin | tape-run | tape-istanbul
```

Produces this result:

<img width="585" alt="screen shot 2016-12-12 at 07 10 26" src="https://cloud.githubusercontent.com/assets/761444/21099058/1926b9ba-c03a-11e6-9b3c-4aaeb56fc6b7.png">

Remove the `| tape-istanbul` and the exit code is `1`. Any idea why?

**Comment by bendrucker** [comment]
Hmm I'm thinking that you'd need to use`pipefail`. Don't think there's anything I can do here short of reparsing the output. Can't see the exit code of the previous pipeline step.

**Comment by bendrucker** [comment]
That's definitely it, see https://github.com/yoshuawuyts/choo/pull/360

**Comment by timwis** [comment]
Interesting, hadn't heard of `pipefail`. In that case, I wonder: will there ever be a case where someone uses `tape-istanbul` cli that _doesn't_ need to set `pipefail`? If that's the case, should it be included in the docs?

**Comment by bendrucker** [comment]
It's a bash option so if you're not using bash you'd have no choice. Would totally take a PR though.
